# Generated by Django 6.1 on 2026-08-22 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_ip', models.GenericIPAddressField(blank=True, help_text='IP address of the creator', null=True)),
                ('created_location', models.CharField(blank=True, help_text='Approximate location of the creator', max_length=255, null=True)),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=150)),
                ('region', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cities/')),
                ('cost_index', models.PositiveIntegerField(default=50, help_text='0-100 scale of how expensive it is')),
                ('popularity', models.PositiveIntegerField(default=50, help_text='0-100 scale of popularity')),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SavedDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_ip', models.GenericIPAddressField(blank=True, help_text='IP address of the creator', null=True)),
                ('created_location', models.CharField(blank=True, help_text='Approximate location of the creator', max_length=255, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='destinations.city')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_destinations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'city')},
            },
        ),
    ]
