# Generated by Django 6.1 on 2026-08-22 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_external_image_url'),
        ('destinations', '0003_alter_city_id_alter_saveddestination_id'),
    ]

    operations = [
    ]
