# Generated by Django 6.1 on 2026-08-22 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_alter_city_id_alter_saveddestination_id'),
        ('destinations', '0004_merge_20260822_1653'),
    ]

    operations = [
    ]
