# Generated by Django 6.1 on 2026-08-22 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_ip', models.GenericIPAddressField(blank=True, help_text='IP address of the creator', null=True)),
                ('created_location', models.CharField(blank=True, help_text='Approximate location of the creator', max_length=255, null=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('activity_type', models.CharField(choices=[('Sightseeing', 'Sightseeing'), ('Food', 'Food'), ('Adventure', 'Adventure'), ('Museum', 'Museum'), ('Shopping', 'Shopping'), ('Nature', 'Nature'), ('Entertainment', 'Entertainment'), ('Nightlife', 'Nightlife'), ('Other', 'Other')], default='Sightseeing', max_length=50)),
                ('duration', models.PositiveIntegerField(default=60, help_text='Estimated duration in minutes')),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='activities/')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='destinations.city')),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['name'],
            },
        ),
    ]
