# Generated by Django 6.1 on 2026-08-22 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_external_image_url'),
        ('activities', '0003_alter_activity_id'),
    ]

    operations = [
    ]
