# Generated by Django 6.1 on 2026-08-22 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_ip', models.GenericIPAddressField(blank=True, help_text='IP address of the creator', null=True)),
                ('created_location', models.CharField(blank=True, help_text='Approximate location of the creator', max_length=255, null=True)),
                ('category', models.CharField(choices=[('Transport', 'Transport'), ('Accommodation', 'Accommodation'), ('Activities', 'Activities'), ('Meals', 'Meals'), ('Other', 'Other')], default='Other', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='trips.trip')),
                ('trip_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='trips.tripstop')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
