# Generated by Django 6.1 on 2026-08-22 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='communitypost',
            new_name='community_c_categor_c6128e_idx',
            old_name='community_c_category_7ae2f6_idx',
        ),
        migrations.RenameIndex(
            model_name='communitypost',
            new_name='community_c_is_publ_31dad5_idx',
            old_name='community_c_is_published_8e41e8_idx',
        ),
    ]
