# Generated by Django 6.1 on 2026-08-22 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_rename_community_c_category_7ae2f6_idx_community_c_categor_c6128e_idx_and_more'),
        ('community', '0002_social_realtime'),
    ]

    operations = [
    ]
