# Generated by Django 6.1 on 2026-08-22 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_merge_20260822_1547'),
        ('community', '0003_share_and_trip_notifications'),
    ]

    operations = [
    ]
