# Generated by Django 6.1 on 2026-08-22 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_merge_20260822_1653'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='communitynotification',
            new_name='community_c_recipie_aef0bd_idx',
            old_name='community_c_recipient_56a6cb_idx',
        ),
        migrations.RenameIndex(
            model_name='communitynotification',
            new_name='community_c_recipie_32784d_idx',
            old_name='community_c_recipient_4be6e4_idx',
        ),
    ]
